version: '2'

services:
  mongo:
    build:
      context: ./mongo
      args:
        - MONGO_USER=$MONGO_USER
        - MONGO_PASS=$MONGO_PASS
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data

  node:
    depends_on:
      - mongo
    build:
      context: .
    env_file:
      - .env
    ports:
      - $PORT:$PORT
    volumes:
      - .:/srv
      - express_modules:/srv/express/node_modules
      - react_modules:/srv/react/node_modules
      - root_modules:/srv/node_modules
      - react_build:/srv/react/build

# Some directories must be persisted outside of the
# regular container images. This prevents building a
# new container on one hand and running a command every time
# a container boots on the other hand.
volumes:
  # Run `npm install` from a booted container to update dependencies.
  express_modules:
  react_modules:
  root_modules:
  # Run `npm build` from a booted container to update static assets.
  react_build:
  # Mongo will persist its data without changing its container image.
  mongo_data:
